name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get GHH version
      run: ./version-parse-step.sh
      id: version

    - name: Debug VERSION
      run: echo ${{ steps.version.outputs.version }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: grepnull
        password: ${{ secrets.DOCKER_KEY }}
        repository: grepnull/gloomhaven-helper-headless
        always_pull: true
        cache_froms: grepnull/gloomhaven-helper-headless:auto-ci,openjdk:14.0.2-slim-buster
        build_args: "version=${{ steps.version.outputs.version }},BUILDKIT_INLINE_CACHE=1"
        tag_with_ref: true
        tag_with_sha: true
        tags: "${{ steps.version.outputs.version }},${{ steps.version.outputs.major }},${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
        add_git_labels: true

    - name: Build and push Docker images
      uses: aevea/action-kaniko@v0.5.1
      with:
        username: grepnull
        password: ${{ secrets.DOCKER_KEY }}
        image: grepnull/gloomhaven-helper-headless
        cache: true
        cache_registry: grepnull/cache
        extra_args: "--build-arg version=${{ env.VERSION }} --destination grepnull/gloomhaven-helper-headless:${{ env.VERSION}}"
###  --destination grepnull/gloomhaven-helper-headless:${{ steps.version.outputs.major }} --destination grepnull/gloomhaven-helper-headless:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
        # skip_unchanged_digest: true ### Broken as of v0.5.1

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      if: github.ref == 'refs/heads/master'
      env:
        DOCKERHUB_USERNAME: grepnull
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: grepnull/gloomhaven-helper-headless
