name: Update Version

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest GHH version
      uses: ./latest-gloomhaven-helper-action
      id: version

    - name: Update version
      run: echo ${{ steps.version.outputs.version }} > VERSION

    - name: Git commit and push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GHH_GITHUB_TOKEN }}
        push-branch: master
        commit-message: "Update version to ${{ steps.version.outputs.version }}"
        files: VERSION
        name: vince rosso
        email: vincer@vincer.net
